// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_genres.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addGenreToGame = `-- name: AddGenreToGame :one
INSERT INTO game_genres (game_id, genre_id)
VALUES (
  $1,
  $2
)
RETURNING game_id, genre_id
`

type AddGenreToGameParams struct {
	GameID  uuid.UUID
	GenreID uuid.UUID
}

func (q *Queries) AddGenreToGame(ctx context.Context, arg AddGenreToGameParams) (GameGenre, error) {
	row := q.db.QueryRow(ctx, addGenreToGame, arg.GameID, arg.GenreID)
	var i GameGenre
	err := row.Scan(&i.GameID, &i.GenreID)
	return i, err
}
