// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: games.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (id, title, genre, copies)
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3
)
RETURNING id, title, genre, copies
`

type CreateGameParams struct {
	Title  string
	Genre  sql.NullString
	Copies int16
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, arg.Title, arg.Genre, arg.Copies)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Genre,
		&i.Copies,
	)
	return i, err
}

const deleteGameById = `-- name: DeleteGameById :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGameById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameById, id)
	return err
}

const getAllGames = `-- name: GetAllGames :many
SELECT id, title, genre, copies from games
`

// maybe add functionality to pass in what to sort by?
func (q *Queries) GetAllGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Genre,
			&i.Copies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameById = `-- name: GetGameById :one
SELECT id, title, genre, copies FROM games where id = $1
`

func (q *Queries) GetGameById(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameById, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Genre,
		&i.Copies,
	)
	return i, err
}

const updateGame = `-- name: UpdateGame :one
UPDATE games 
SET title = COALESCE(NULLIF($1, ''), title),
    genre = COALESCE(NULLIF($2, ''), genre),
    copies = COALESCE(NULLIF($3, ''), copies)
WHERE id = $4
RETURNING id, title, genre, copies
`

type UpdateGameParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	ID      uuid.UUID
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.ID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Genre,
		&i.Copies,
	)
	return i, err
}
