// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
}

type Game struct {
	ID     uuid.UUID
	Title  string
	Copies int16
}

type GameGenre struct {
	GameID  uuid.UUID
	GenreID uuid.UUID
}

type Genre struct {
	ID   uuid.UUID
	Name string
}

type Reservation struct {
	ID         uuid.UUID
	StartTime  time.Time
	EndTime    time.Time
	CustomerID uuid.NullUUID
	GameID     uuid.NullUUID
}
