// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reservations.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkGameReservation = `-- name: CheckGameReservation :one
SELECT
  COUNT(*) as reserved_count
FROM reservations
WHERE reservations.game_id = $1
AND reservations.start_time < $2
AND reservations.end_time > $3
HAVING
  COUNT(*) < (SELECT copies from games WHERE id = $1)
`

type CheckGameReservationParams struct {
	GameID    pgtype.UUID
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
}

func (q *Queries) CheckGameReservation(ctx context.Context, arg CheckGameReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkGameReservation, arg.GameID, arg.StartTime, arg.EndTime)
	var reserved_count int64
	err := row.Scan(&reserved_count)
	return reserved_count, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
  id, 
  start_time, 
  end_time, 
  user_id, 
  game_id
  )
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3,
  $4
)
RETURNING id, start_time, end_time, user_id, game_id
`

type CreateReservationParams struct {
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
	UserID    pgtype.UUID
	GameID    pgtype.UUID
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
		arg.GameID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
		&i.GameID,
	)
	return i, err
}

const getAllActiveReservations = `-- name: GetAllActiveReservations :many
SELECT id, start_time, end_time, user_id, game_id from reservations where end_time > NOW()
`

func (q *Queries) GetAllActiveReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getAllActiveReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.UserID,
			&i.GameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReservations = `-- name: GetAllReservations :many
SELECT id, start_time, end_time, user_id, game_id from reservations
`

func (q *Queries) GetAllReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getAllReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.UserID,
			&i.GameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationsForUser = `-- name: GetReservationsForUser :many
SELECT reservations.id, reservations.start_time, reservations.end_time, reservations.user_id, reservations.game_id,
       games.title as game_name
FROM reservations
JOIN
  games
ON
  reservations.game_id = games.id
where user_id = $1
`

type GetReservationsForUserRow struct {
	ID        uuid.UUID
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
	UserID    pgtype.UUID
	GameID    pgtype.UUID
	GameName  string
}

func (q *Queries) GetReservationsForUser(ctx context.Context, userID pgtype.UUID) ([]GetReservationsForUserRow, error) {
	rows, err := q.db.Query(ctx, getReservationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservationsForUserRow
	for rows.Next() {
		var i GetReservationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.UserID,
			&i.GameID,
			&i.GameName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
