// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reservations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
  id, 
  start_time, 
  end_time, 
  user_id, 
  game_id
  )
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3,
  $4
)
RETURNING id, start_time, end_time, user_id, game_id
`

type CreateReservationParams struct {
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
	UserID    pgtype.UUID
	GameID    pgtype.UUID
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
		arg.GameID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
		&i.GameID,
	)
	return i, err
}
